name: Schedule on multiple branches

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ main, dev, test, "spikes/mytest" ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - run: git checkout $(git describe --abbrev=0 --tags)
      - run: env | sort
