name: Test matrix

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [ { branch: main, java: 8 }, { branch: dev, java: 11} ]

    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.config.java }}
          distribution: 'temurin'
      - run: echo ${{ matrix.config.branch }}
